dms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filemanager.urls'))
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filemanager/urls.py
from django.urls import path
# from django.conf.urls import url
from . import views

urlpatterns = [
    path('login/', views.loginPage),
    path('register/', views.registration_view),
    path('logout/', views.logoutPage),
    path('', views.load_user_dashboard),
    path('add-file/', views.add_file),
    path('settings/', views.settings),
    path('share-file/', views.share_file),
    path('search/', views.settings),

]

filemanager/models.py
from enum import unique
from os import access
from unicodedata import category
from django.db import models
import django
import datetime
import secrets
from django.contrib.auth.models import AbstractUser, Group, Permission
from sqlalchemy import null


# Create your models here.
class Department(models.Model):
	name= models.CharField(max_length=100, unique=True)

	def __str__(self):
		return self.name

class Employee(AbstractUser):
	phone_no = models.CharField(max_length=10, null=True, blank=True)
	department = models.ForeignKey(Department, related_name='employees',on_delete=models.DO_NOTHING, blank=True, null=True)
	groups = models.ManyToManyField(Group)
	user_permissions = models.ManyToManyField(Permission)

class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    slug = models.SlugField()

class Access(models.Model):
    status = models.CharField(max_length=10, unique=True)

class File(models.Model):
    name = models.CharField(max_length=25, unique=True)
    description = models.TextField()
    slug = models.SlugField(unique=True)
    file_location = models.FileField(upload_to='myfiles', null=True, blank=True)
    category = models.ForeignKey(Category, related_name='files', on_delete=models.DO_NOTHING, blank=True, null=True)
    added_by = models.ForeignKey(Employee, related_name='files', on_delete=models.DO_NOTHING, blank=True, null=True)
    department = models.ForeignKey(Department, related_name='files', on_delete=models.DO_NOTHING, blank=True, null=True) 
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    shared_to = models.ManyToManyField(Employee, through='FileShare')

    def __str__(self):
        return self.name

class FileShare(models.Model):
    file = models.ForeignKey(File, related_name='fileshares', on_delete=models.DO_NOTHING)
    user = models.ForeignKey(Employee, related_name='fileshares', on_delete=models.DO_NOTHING)
    access = models.ForeignKey(Access, related_name='files', on_delete=models.DO_NOTHING, blank=True, null=True)       
    date_shared = models.DateTimeField(auto_now_add=True)

filemanager/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from .models import *


class UserGroupForm(ModelForm):
	class Meta:
		model = Group
		fields = '__all__'

class AddFile(ModelForm):
	class Meta:
		model = File
		fields = ('name', 'description', 'slug','file_location')
		widgets = {
			'name': forms.TextInput(attrs={"class":"form-control mb-3", "placeholder":"Enter your file name here..."}),
			'description': forms.Textarea(attrs={'class':"form-control mb-3", "rows":"5", "placeholder": "Provide a short description of your file"}),
			'slug': forms.TextInput(attrs={'placeholder': 'example, this-is-my-file', "class":"form-control mb-3"}),
			'file_location': forms.FileInput(attrs={'class': 'form-control mb-3'}),
		}
        

# forms

filemanager/views.py
import imp
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import *
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import *
from . import utils


# Create your views here.
def registration_view(request):
    msg = None
    if request.method == 'POST':
        route_link = request.POST.get('link-tag')
        user_pass = request.POST.get('user-pass')
        user_name = request.POST.get('username')
        department = request.POST.get('department')
        org = request.POST.get('organization')
        user_mail = request.POST.get('email')
        user_phone = request.POST.get('phone_no')
        msg = 'An error occurred during registration of user'
        try:
            if department != "":
                department = Department.objects.get(name=department)
            else:
                department = None 
            employee = Employee.objects.create_user(username=user_name.lower(), email=user_mail, phone_no=user_phone, password=user_pass,department=department)
            msg = f'You have successfully created user {employee.username}'
        except:
            pass
        if route_link is not None:
            messages.success(request, msg)
            return redirect(f'/{route_link}/')
        messages.success(request, msg)
        return redirect('/register/')
    return render(request, 'dms/register.html', {})

def loginPage(request):
    msg = None
    if request.method == 'POST':
        requesting_user = request.POST.get('username').lower()
        requesting_user_password= request.POST.get('user-pass')
        if Employee.objects.filter(username=requesting_user).exists():
            user = Employee.objects.get(username=requesting_user)
            authenticated_user = authenticate(request, username=requesting_user, password=requesting_user_password)
            if authenticated_user is not None:
                login(request, authenticated_user)
                msg = "Successfully logged in"
                try:
                    del request.session[requesting_user]
                except:    
                    active = request.session[requesting_user] = requesting_user
                return redirect('/')
            else:
                pass
        msg = "The password or the username you entered is incorrect"
        messages.success(request, msg)
        return redirect('/login/')

    return render(request, 'dms/login.html', {})

def logoutPage(request):
    try:
        del request.session[request.user]
    except:
        pass
    logout(request)
    return redirect('/login/')


def share_file(request):
    if request.method == 'POST':
        file_slug = request.POST.get('file-slug')
        share_to_this_user = request.POST.get('user')
        sharing_user = Employee.objects.get(username=request.user)
        user = Employee.objects.get(username=share_to_this_user)
        file = File.objects.get(slug=file_slug)
        print(request.user, file.added_by.username)
        if file.added_by.username != sharing_user.username:
            messages.error(request, "You do not have the permission to share this file, request file owner to make the share")
            return redirect('/')

        if FileShare.objects.filter(file=file, user=user).exists():
            messages.error(request, "You have already shared the file")
            return redirect('/')
        fileshare = FileShare.objects.create(file=file, user=user)
        fileshare.save()
        messages.success(request, f"You have successfully shared a file with {user.username}")
    return redirect('/')

@login_required(login_url='/login/')
def load_user_dashboard(request):
    user = Employee.objects.get(username=request.user)
    files = File.objects.filter(added_by=user)
    shared = File.objects.filter(shared_to__username=user.username)
    files = files | shared
    paginator = Paginator(files, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    users = Employee.objects.all()

    return render(request, 'dms/admin.html', {'files': page_obj, 'user_files': files, 'logged_user': user, 'users': users})

@login_required(login_url='/login/')
def add_file(request):
    form = AddFile()
    if request.method == 'POST':
        form = AddFile(request.POST, request.FILES)
        if form.is_valid():
            file_owner = Employee.objects.get(username=request.user)
            new_file = form.save()
            new_file.added_by = file_owner
            new_file.save()
            messages.success(request, 'File was added successfully')
            return redirect('/add-file/')

    return render(request, 'dms/add-file.html', {'form': form})

@login_required(login_url='/login/')
def settings(request):
    return render(request, 'dms/settings.html', {})

filemanager/templates/dms/add-file.html
{% extends 'dms/admin.html' %}

{% block title %} Add File | {% endblock %}

{% block content %}
{% load static %}
<h2>Add a file</h2><br>
<!-- <form action="" method="get">
    {{filter.form}}
    <input type="submit" value="filter">
</form><br> -->
<div class="card">
    <div class="card-body">
        <form action="/add-file/" method="post" enctype="multipart/form-data">
          {% csrf_token %}

          {{form.name}}

          {{form.description}}

          {{form.slug}}

          {{form.file_location}}


            <input type="submit" class="btn btn-info" value="Add file">
        </form>				
    </div>
</div><br>
{% for message in messages %}
<ul>
  <li><h5>{{message}}</h5></li>
</ul>
{% endfor %}

<a href="/">Go back to the home page</a>


{% endblock %}

filemanager/templates/dms/admin.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <title>{% block title %} {% endblock %} DMS</title>
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">DMS | Dashboard</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/add-file/">Add a File</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  More Actions
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/search/">Search for a file</a></li>
                  <li><a class="dropdown-item" href="">Add file category</a></li>
                  <li><a class="dropdown-item" href="">View system Logs</a></li>
                </ul>
              </li>
            </ul>


            <div class="d-flex">
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Welcome {{logged_user}}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="/reset-pass/">Change Password</a></li>
                      <li><a class="dropdown-item" href="/logout/">Logout</a></li>
                    </ul>
                  </li>
                </ul>    
            </div>


        </div>
        </div>
      </nav> 
      
      <div class="row">
        <div class="col-lg-2 mt-2">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header bg-info">
                          Quick Summary
                        </div>
                        <ul class="list-group list-group-flush">
                          <li class="list-group-item">All my files <span class="badge bg-success">{{user_files.count}} </span></li>
                        </ul>
                      </div>        
                </div>
                <!-- end of col -->
            </div>
            <!-- first row in first col -->
            <div class="row">
                <div class="col-lg-12 mt-2">
                    <div class="card">
                        <div class="card-header bg-info">
                          Quick Actions
                        </div>
                        <ul class="list-group list-group-flush">
                          <li class="list-group-item"><a href="/manage-users/">Manage Users</a></li>
                          <li class="list-group-item"><a href="/settings/">Settings</a></li>
                        </ul>
                      </div>        
                </div>
                <!-- end of col -->
            </div>
            <!-- second row in first col -->
        </div>
        <!-- end of first column div -->
        <div class=" col-8 col-lg-10 mt-2">
          {% block content %}
            <h2>Recent Files</h2><br>
            {% for message in messages %}
            <div class="alert alert-dark mt-2">
              <h5>{{message}}</h5>
            </div>
           {% endfor %}
        
            <!-- <form action="" method="get">
                {{filter.form}}
                <input type="submit" value="filter">
            </form><br> -->
            <div class="table-responsive">
                <table class="table table-sm">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">File Name</th>
                        <th scope="col">File Description</th>
                        <th scope="col">Added</th>
                        <th scope="col">View file</th>
                    </tr>
                    </thead>
                    <tbody>
                      {% for file in files %}
                      <tr>
                        <th scope="row">{{file.id}} </th>
                        <td>{{file.name}}</td>
                        <td>{{file.name}}</td>
                        <td>{{file.created_at | timesince}} ago </td>
                        <td>
                          <button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#modal{{file.id}}">Share</button>
                        </td>            
                        <td><a href="{{file.file_location.url}}">View file</a></td>
                      </tr>

                    <!-- incident modal goes here -->
                    <div class="modal" id="modal{{file.id}}">
                      <div class="modal-dialog modal-lg">
                        <div class="modal-content">

                          <!-- Modal Header -->
                          <div class="modal-header">
                            <h4 class="modal-title">Share a file</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                          </div>

                          <!-- Modal body -->
                          <div class="modal-body">
                            {% include 'dms/modals/share-file.html' %}
                          </div>

                        </div>
                      </div>
                    </div>


                      {% empty %}
                      <tr>
                        <td><h3>No file found</h3></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="pagination">
                    <span class="step-links">
                        {% if files.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ files.previous_page_number }}">previous</a>
                        {% endif %}
                
                        <span class="current">
                            Page {{ files.number }} of {{ files.paginator.num_pages }}.
                        </span>
                
                        {% if files.has_next %}
                            <a href="?page={{ files.next_page_number }}">next</a>
                            <a href="?page={{ files.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                  </div>
                      <!-- pagination div ends here -->
            </div>
            <!-- end of table div -->
            {% endblock %}
        </div>
        <!-- end of second col div -->
      </div>
      <!-- end of outer row div -->
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

filemanager/templates/dms/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <title>{% block title %} {% endblock %} DMS</title>
  </head>
  <body>
    {% block content %}

    {% endblock %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  </body>
</html>

filemanager/templates/dms/login.html
{% extends 'dms/base.html' %}

{% block title %} LOGIN | {% endblock %}

{% block content %}

<div class="container">
	<div class="row justify-content-center mt-5">
		<div class="col-lg-8 align-self-center mt-5">
			<div class="card mt-5">
				<div class="card-header bg-info">
					<center><h1> User Login</h1></center>
				</div>
				<div class="card-body">
					<form action="/login/" method="post">
						{% csrf_token %}
						<div class="form-group row">
						  <label for="inputEmail3" class="col-sm-2 col-form-label">Username</label>
						  <div class="col-sm-10">
							<input type="text" class="form-control" name="username"  placeholder="Your username" required>
						  </div>
						</div><br>
  
						  <div class="form-group row">
							<label for="inputPassword3" class="col-sm-2 col-form-label">Enter your Password</label>
							<div class="col-sm-10">
							  <input type="password" class="form-control" name="user-pass" placeholder="Password" required>
							</div>
						  </div><br>  
						<div class="form-group row">
						  <div class="col-sm-10">
							<button type="submit" class="btn btn-info">Sign in</button>
								or
								<a href="/register/">Register</a>
						  </div>
						</div>
					</form>				
				</div>
			</div><br>			
			<!-- col div ends here -->
				<ul>
					{% for msg in messages %}
					<li><h3>{{msg}}</h3></li>
					{% endfor %}
				</ul>
										

		</div>
		<!-- row div ends here -->
	</div>
	<!-- container div ends here -->
</div>

{% endblock %}

filemanager/templates/dms/modals/share-file.html
<form action="/share-file/" method="POST" class="pt-3"> 
    {% csrf_token %}
  
  <div class="form-group mb-2">
    <input type="hidden" name="file-slug" value="{{file.slug}}">
    <label for="user">Select a user to share the file with:</label>
    <select class="form-control form-control-lg"  name="user" required>
      <option value="">Select user</option>
      {% for user in users %}
      {% if user.username != logged_user %}
      <option value="{{user.username}}">{{ user.username }}</option>
      {% endif %}
      {% endfor %}
    </select>
  </div>
  <!-- <div class="form-group mb-2">
    <input type="password" class="form-control form-control-lg" id="user_pass" name="user-pass" placeholder="Password" required>
  </div> -->

  <div class="">
    <button class="btn btn-block btn-info btn-lg font-weight-medium auth-form-btn" type="submit">Share file</button>
  </div>
</form>

filemanager/templates/dms/modals/user.html
<form action="/register/" method="POST" class="pt-3"> 
    {% csrf_token %}
    <input type="hidden" value="manage-users" name="link-tag">
  <div class="form-group mb-2">
    <input type="text" class="form-control form-control-lg" id="user_name" name="username" placeholder="Your username" required>
  </div>
  <div class="form-group mb-2">
    <input type="email" class="form-control form-control-lg" id="user_mail" name="email" placeholder="Your email">
  </div>

  <div class="form-group mb-2">
    <input type="tel" class="form-control form-control-lg" id="user_mail" name="phone_no" placeholder="Your phone number">
  </div>
  
  <div class="form-group mb-2">
    <select class="form-control form-control-lg" id="id_organization" name="organization" required>
      <option value="">Select Organization</option>
      {% for organization in organizations %}
      <option value="{{organization.name}}">{{ organization.name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group mb-2">
    <select class="form-control form-control-lg" id="id_department" name="department" required>
      <option value="">Select user department</option>
      {% for dept in departments %}
      <option value="{{dept.name}}">{{ dept.name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="form-group mb-2">
    <input type="password" class="form-control form-control-lg" id="user_pass" name="user-pass" placeholder="Password" required>
  </div>

  <div class="">
    <button class="btn btn-block btn-warning btn-lg font-weight-medium auth-form-btn" type="submit">Add User</button>
  </div>
</form>

filemanager/templates/dms/register.html
{% extends 'dms/base.html' %}

{% block title %} REGISTER | {% endblock %}

{% block content %}

<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8 align-self-center m-5">
			<ul>
				{% for msg in messages %}
				<li><h3>{{msg}}</h3></li>
				{% endfor %}
			</ul>

			<div class="card">
				<div class="card-header bg-info">
					<center><h1>Register User</h1></center>
				</div>
				<div class="card-body">
					<form action="/register/" method="post">
						{% csrf_token %}
						<div class="form-group row">
						  <label for="inputEmail3" class="col-sm-2 col-form-label">Username</label>
						  <div class="col-sm-10">
							<input type="text" class="form-control" name="username" placeholder="Your username" required>
						  </div>
						</div><br>
						<div class="form-group row">
						  <label for="inputPassword3" class="col-sm-2 col-form-label">Email</label>
						  <div class="col-sm-10">
							<input type="email" class="form-control" name="email" placeholder="Your Email" required>
						  </div>
						</div><br>

						<div class="form-group row">
							<label for="inputPassword3" class="col-sm-2 col-form-label">Phone</label>
							<div class="col-sm-10">
							  <input type="tel" class="form-control" name="phone_no" placeholder="Your Phone Number" required>
							</div>
						</div><br>
  
						  <div class="form-group row">
							<label for="inputPassword3" class="col-sm-2 col-form-label">Department</label>
							<div class="col-sm-10">
								<select class="form-control" name="department" id="id_department">
									<option value="">Select department</option>
									{% for department in departments %}
									<option value="{{department.name}}">{{department.name}}</option>
									{% endfor %}
								</select>
							</div>
						  </div><br>
  
						  <div class="form-group row">
							<label for="inputPassword3" class="col-sm-2 col-form-label">Enter your Password</label>
							<div class="col-sm-10">
							  <input type="password" class="form-control" name="user-pass" placeholder="Password" required>
							</div>
						  </div><br>
  
						<div class="form-group row">
						  <div class="col-sm-10">
							<button type="submit" class="btn btn-info">Register</button>
								or 
								<a href="/login/">Already registered, login</a>
						  </div>
						</div>
					</form>				
				</div>
			</div>			
			<!-- col div ends here -->
		</div>
		<!-- row div ends here -->
	</div>
	<!-- container div ends here -->
</div>

{% endblock %}

filemanager/templates/dms/search.html
{% extends 'dms/admin.html' %}

{% block title %} Add File | {% endblock %}

{% block content %}
{% load static %}
<h2>Add a file</h2><br>
<div class="card">
    <div class="card-body">
        <form action="/search/" method="get">
            <input type="text" name="search-input" placeholder="Search here by file title, description, category or department....">
            <input type="submit" class="btn btn-info" value="Add file">
        </form>				
    </div>
</div><br>
{% for message in messages %}
<ul>
  <li><h5>{{message}}</h5></li>
</ul>
{% endfor %}

<a href="/">Go back to the home page</a>


{% endblock %}

filemanager/templates/dms/settings.html
{% extends 'dms/admin.html' %}

{% block title %} Settings | {% endblock %}

{% block content %}
{% load static %}

<div class="card">
    <div class="card-body">
        <form action="/add-file-category/" method="post">
          {% csrf_token %}
            <label for="file-category">File category name</label>
            <input type="text" name="file-category" class="form-control mb-3" placeholder="Enter category name here">
            <input type="submit" class="btn btn-info" value="submit">
        </form>				
    </div>
</div><br>

<div class="card">
    <div class="card-body">
        <form action="/add-department/" method="post">
          {% csrf_token %}
            <label for="file-category">Department name</label>
            <input type="text" name="new-department" class="form-control mb-3" placeholder="Enter department name here">
            <input type="submit" class="btn btn-info" value="submit">
        </form>				
    </div>
</div><br>

<div class="card">
    <div class="card-body">
        <form action="/add-file-access-status/" method="post">
          {% csrf_token %}
            <label for="file-category">File access status name</label>
            <input type="text" name="file-visibility" class="form-control mb-3" placeholder="Enter access status name here">
            <input type="submit" class="btn btn-info" value="submit">
        </form>				
    </div>
</div><br>

{% for message in messages %}
<ul>
  <li><h5>{{message}}</h5></li>
</ul>
{% endfor %}

<a href="/">Go back to the home page</a>


{% endblock %}